sudo: required
language: java
services:
  - docker

env:
  - TERM=dumb

install:
  - ./deploy.sh

script:
  - ./tests/latency.sh "http://172.17.0.1:10001" "$(cat openwhisk/ansible/files/auth.guest)"
  - ./tests/throughput.sh "http://172.17.0.1:10001" "$(cat openwhisk/ansible/files/auth.guest)" 4
  - ./gradlew gatlingRun -Dwhisk.perftest.baseurl="http://172.17.0.1:10001"